### PR TITLE
Fix invoke magic method order

### PR DESCRIPTION
**Pull request by driftingly**
This PR should resolve the issue with `__invoke` magic method order introduced in PR #230

Additional test `identifies_invoke_method()`.

### CODE REVIEW

**Comment by mattstauffer** [comment]
I'd like `__invoke` to be able to be at the top, unlike the other magic methods.. but am I crazy for that? @bakerkretzmar

**Comment by mattstauffer** [comment]
OHHH is this PR allowing it to be at the top? lol.. if so then yay

**Comment by driftingly** [comment]
@mattstauffer yes, requires it after `__construct()`. 

Current order:

- trait use
- public static property
- protected static property
- private static property
- public constant
- protected constant
- private constant
- public property
- protected property
- private property
- constructor
- invoke
- public static method
- protected static method
- private static method
- public method
- protected method
- private method
- magic method

**Comment by mattstauffer** [comment]
🙌🏻wooooo thanks!!

**Pull request merged**
