### PR TITLE
Check Composer configs before using them

### PR DESCRIPTION
**Pull request by szepeviktor**
kép

### CODE REVIEW

**Comment by szepeviktor** [comment]
Both the version field and the lock file is a no-go in a PHP library.

**Comment by mattstauffer** [comment]
Composer Lock file will just be ignored so it's not a big deal either way.

But I would be we should get rid of the version, we'll talk about it. Thanks!

**Comment by loganhenson** [comment]
We use the version field of `composer.json` for the CLI (rather than a magic constant in the code that needs to change.)

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
> We use the version field of composer.json for the CLI (rather than a magic constant in the code that needs to change.)

Maybe it is not true

https://github.com/tighten/tlint/blob/d428a88ddcf7c52ed5bcfce9326864abd3a6a40d/src/helpers.php#L7

There is a standard way to ask Composer about a certain package's version.
I'd gladly send a PR!

**Comment by loganhenson** [comment]
@szepeviktor haha I _just_ changed that code to comply with your PR 😅 . What is the standard way??? I've been searching for it for months haha, no one knows..please PR if you know the secret way 😄

**Comment by szepeviktor** [comment]
Do not every be a Composer (plugin) developer! It feels not so good.
I copy it here shortly:

**Comment by szepeviktor** [comment]
There are - at least - three ways

1) the dirty one

```php
array_column(json_decode(file_get_contents(__DIR__ . '/vendor/composer/installed.json'), true), 'version_normalized', 'name')['tightenco/tlint']
```

2) a Composer event that writes version into `vendor/tightenco/tlint/VERSION` on update and on install `$event->getComposer()->...`

2b) require `composer/composer` and ask for version

3) the Proper way https://github.com/Ocramius/PackageVersions **33 sloc** !!!

**Pull request merged**
