### PR TITLE
Fix magic method order

### PR DESCRIPTION
**Pull request by driftingly**
This PR should resolve issue #229

I added an additional test `handles_magic_methods()`.

### CODE REVIEW

**Comment by Gummibeer** [comment]
This change made invokable controller useless.
```php
public function __invoke(): JsonResponse {}

protected function helper() {};
```

But now The rule wants me to move the `__invoke` method down as it's magic.
At least for controllers this should be a special case - not sure about other classes.

**Comment by driftingly** [comment]
We already have a special case for the `__construct()` magic method, adding an additional one for `__invoke()` could work.
Is there already a defined order or would adding `invoker` below `constructor` make sense?

```php
  protected const THINGS_ORDER = [
        'trait use',
        'public static property',
        'protected static property',
        'private static property',
        'public constant',
        'protected constant',
        'private constant',
        'public property',
        'protected property',
        'private property',
        'constructor',
        'invoker',
        'public static method',
        'protected static method',
        'private static method',
        'public method',
        'protected method',
        'private method',
        'magic method',
    ];
```

**Comment by Gummibeer** [comment]
For me the `__invoke()` should be right after `__construct()` - yes.

**Comment by loganhenson** [comment]
That makes sense to me as well, good catch

**Pull request merged**
